---
- hosts: debian
  become: yes
  tasks:
    - name: Install basic necessities
      apt:
        pkg:
          - vim
          - firefox-esr
          - terminator
          - tmux
        state: latest
    - name: Install xmonad and relateds
      apt:
        pkg:
          - xmonad
          - libghc-xmonad-contrib-dev
          - libghc-xmonad-dev
          - nitrogen
          - xmobar
          - suckless-tools  # dmenu
        state: latest

